### ISSUE TITLE
Create "About" page

### ISSUE THREAD

**Issue by laurentS** [mapswipe/mapswipe.org#18]
3 main sections:
- Jess's updated content "About"
- People sections (the major contributors)
- Partners section (the logos of major contributing organisations, that are currently on the main page)

Sub ticket of #17

**Comment by Matthias-Schaub** [comment]
There are two GoogleDocs on following topics:
1. "For MapSwipe requesters"
    - Requesting a MapSwipe mission
    - Following the swiping progress
    - Downloading and using MapSwipe data
2. "For MapSwipe managers"
    - Managing MapSwipe missions 
    - Troubleshooting
    - Sending in-app notifications

There is some content relevent for the about page.

**Comment by jhenshall** [comment]
Done as part of new website. More defined tasks to follow.
