### ISSUE TITLE
Create "Get involved" page

### ISSUE THREAD

**Issue by laurentS** [mapswipe/mapswipe.org#19]
5 sections:

## Swipe
Links to download the app, and a short blurb

## For organisations
Any org can request help with mapping a project in mapswipe.
How to request, and links to forms/resources

## For developers
links to github.com/mapswipe , the API, and a short blurb on how to help

## For translators
Link to https://www.transifex.com/mapswipe/mapswipe-app/ where you can volunteer to translate the app (or this website) in your own language.

## For socialising: Events

Link to the events page, where people can choose to join.

Sub ticket of #17

**Comment by Matthias-Schaub** [comment]
There are two GoogleDocs on following topics:
1. "For MapSwipe requesters"
    - Requesting a MapSwipe mission
    - Following the swiping progress
    - Downloading and using MapSwipe data
2. "For MapSwipe managers"
    - Managing MapSwipe missions 
    - Troubleshooting
    - Sending in-app notifications

Those could be good content drafts.

**Comment by jhenshall** [comment]
Mostly done as part of new website. Refined scope for translation #27
